source 'http://rubygems.org'

gem 'rails', '3.2.6'
gem 'sqlite3'
gem 'json'
gem 'dalli', '~> 1.0.4'
gem 'aws-sdk'
gem 'storehouse', :path => './../../'
gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'thin'
  gem 'riak-client'

end
